version: '2'
services:
    oasis_sim_app-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb oasis_sim_app-mongodb-config
    oasis_sim_app-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    oasis_sim_app-mongodb-config:
        image: mongo:3.2.10
        container_name: oasis_sim_app-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
