version: '2'
services:
    oasis_sim_app-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/oasis_sim_app/mongodb/:/data/db/
